-- Migration: Add vocabulary_memory_tips table
-- Description: Stores user-customized memory tips for vocabulary words
-- Date: 2025-01-19

-- Create vocabulary_memory_tips table
CREATE TABLE IF NOT EXISTS vocabulary_memory_tips (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL,
  word TEXT NOT NULL,
  tip TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT vocabulary_memory_tips_user_word_unique UNIQUE (user_id, word)
);

-- Create index on user_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_vocabulary_memory_tips_user_id
ON vocabulary_memory_tips(user_id);

-- Create index on word for potential future queries
CREATE INDEX IF NOT EXISTS idx_vocabulary_memory_tips_word
ON vocabulary_memory_tips(word);

-- Create index on updated_at for potential sorting/filtering
CREATE INDEX IF NOT EXISTS idx_vocabulary_memory_tips_updated_at
ON vocabulary_memory_tips(updated_at DESC);

-- Add Row Level Security (RLS) policies
ALTER TABLE vocabulary_memory_tips ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only view their own memory tips
CREATE POLICY "Users can view their own memory tips"
ON vocabulary_memory_tips
FOR SELECT
USING (auth.uid()::TEXT = user_id);

-- Policy: Users can insert their own memory tips
CREATE POLICY "Users can insert their own memory tips"
ON vocabulary_memory_tips
FOR INSERT
WITH CHECK (auth.uid()::TEXT = user_id);

-- Policy: Users can update their own memory tips
CREATE POLICY "Users can update their own memory tips"
ON vocabulary_memory_tips
FOR UPDATE
USING (auth.uid()::TEXT = user_id)
WITH CHECK (auth.uid()::TEXT = user_id);

-- Policy: Users can delete their own memory tips
CREATE POLICY "Users can delete their own memory tips"
ON vocabulary_memory_tips
FOR DELETE
USING (auth.uid()::TEXT = user_id);

-- Add comment to table
COMMENT ON TABLE vocabulary_memory_tips IS 'Stores custom AI-generated memory tips for vocabulary words, personalized per user';

-- Add comments to columns
COMMENT ON COLUMN vocabulary_memory_tips.user_id IS 'Firebase user ID from auth system';
COMMENT ON COLUMN vocabulary_memory_tips.word IS 'Vocabulary word (normalized to lowercase)';
COMMENT ON COLUMN vocabulary_memory_tips.tip IS 'Custom memory tip text generated by OpenAI or user-edited';
COMMENT ON COLUMN vocabulary_memory_tips.created_at IS 'Timestamp when the custom tip was first created';
COMMENT ON COLUMN vocabulary_memory_tips.updated_at IS 'Timestamp when the tip was last updated';
