-- Migration: Recreate vocabulary_memory_tips table from scratch
-- Description: Drop and recreate the table without RLS, designed for Firebase Auth
-- Date: 2025-01-09

-- Drop the existing table completely (this will also drop all policies and indexes)
DROP TABLE IF EXISTS vocabulary_memory_tips CASCADE;

-- Create the table fresh with proper structure
CREATE TABLE vocabulary_memory_tips (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL,
  word TEXT NOT NULL,
  tip TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT vocabulary_memory_tips_user_word_unique UNIQUE (user_id, word)
);

-- Create indexes for fast lookups
CREATE INDEX idx_vocabulary_memory_tips_user_id ON vocabulary_memory_tips(user_id);
CREATE INDEX idx_vocabulary_memory_tips_word ON vocabulary_memory_tips(word);
CREATE INDEX idx_vocabulary_memory_tips_updated_at ON vocabulary_memory_tips(updated_at DESC);

-- Add table comment explaining the security model
COMMENT ON TABLE vocabulary_memory_tips IS $$Custom AI-generated memory tips for vocabulary words.
Uses Firebase Auth for authentication (client-side).
RLS is NOT enabled - security enforced by client code.$$;

-- Add column comments
COMMENT ON COLUMN vocabulary_memory_tips.user_id IS 'Firebase user ID from auth system';
COMMENT ON COLUMN vocabulary_memory_tips.word IS 'Vocabulary word (normalized to lowercase)';
COMMENT ON COLUMN vocabulary_memory_tips.tip IS 'Custom memory tip text generated by OpenAI';
COMMENT ON COLUMN vocabulary_memory_tips.created_at IS 'Timestamp when the custom tip was first created';
COMMENT ON COLUMN vocabulary_memory_tips.updated_at IS 'Timestamp when the tip was last updated';

-- Verify table was created
SELECT
  'Table created successfully!' as status,
  COUNT(*) as row_count
FROM vocabulary_memory_tips;
